version: '3'

#To run the flask container
services:
  web:
    build: .
    image: myflaskapp
    restart: always
    container_name: myflaskapp
    
    #This portion here is so you can edit the flask app as needed and just re-run docker compose
    volumes:
      - ./app:/docker-flask-test
    ports:
      - "443:5000"
    depends_on:
      - db
    environment:
      FLASK_APP: view.py
      FLASK_ENV: development
      
  #Runs the postgresql container
  db:
    image: flaskpostgresdb
    restart: always
    container_name: flaskdb
    
    #Fixed volume so you can keep the data in the database.
    volumes:
      - ./data:/var/lib/postgresql/data  
    environment:
      POSTGRES_PASSWORD: MYDATABASEPASSWORD
      POSTGRES_DB: mydatabase
